# Generated by Django 4.2.6 on 2023-10-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='request_api.apimodel')),
                ('key', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
            bases=('request_api.apimodel',),
        ),
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='request_api.apimodel')),
                ('key', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
            bases=('request_api.apimodel',),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('apimodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='request_api.apimodel')),
                ('url', models.CharField(max_length=1000)),
                ('url_encript', models.CharField(max_length=1000)),
                ('bodies', models.ManyToManyField(to='request_api.body')),
                ('headers', models.ManyToManyField(to='request_api.headers')),
            ],
            bases=('request_api.apimodel',),
        ),
    ]
